### ISSUE TITLE
Had a problem completing 'challenge'

### ISSUE THREAD

**Issue by upekshapriya** [krebbi/le-serverpilot#7]
The script hadn't updated Lets' Encrypt automatically and I found I had a 0 days warning email from Let's Encrypt, so I went in to update it manually.

I got the following result:
```
proccessing nginx
proccessing Apache
Restarting nginx-sp: nginx-sp.
All Done! SSL is now disabled
 + Using config file /root/le-serverpilot/config.sh
1
 + Challenge directory found
 + Processing clearvisiontrust.org with SAN: www.clearvisiontrust.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Nov 21 21:55:00 2017 GMT Certificate will expire
(Less than 14 days). Renewing!
 + Challenge directory found
 + Signing domains...
 + Generating signing request...
 + Requesting challenge for clearvisiontrust.org...
 + Responding to challenge for clearvisiontrust.org...
 ERROR Challenge is invalid! (returned: invalid)


 ###############################################################
 ##   THIS WILL ADD HTTPS TO A CUSTOM VHOST FOR SERVERPILOT   ##
 ##                                                           ##
 ##             ** USE AT YOUR OWN RISK **                    ##
 ##                                                           ##
 ###############################################################

 + Adding Strict-Transport-Security 6 Month Policy
proccessing nginx
proccessing Apache
Restarting nginx-sp: nginx-sp.
All Done! SSL is now enabled for Lets Encrypt
```

which didn't update the certificate after all.

I see it says  `ERROR Challenge is invalid! (returned: invalid)` which I guess may have been happening during the auto update. Anyway I turned on my Cloudflare account to Flexible so it wouldn't be a problem with the lack of a valid certificate and then tried it again and found that the Challenge this time was valid so that the certificate updated.

Any idea what went wrong? Why would sometimes the Challenge be invalid and other times valid?

**Comment by krebbi** [comment]
I have no idea why it failed in this situation. But TBH I haven't tested the script in a cloudflare environment. 
It looks like you have a problem with the challenge response to authenticate the request.

**Comment by krebbi** [comment]
And yes: error handling is quite bad in this one...

**Comment by 12steprecovery** [comment]
Thanks for responding. As I said it worked the second time, so all's well, so I'll check it when it's coming up to renew and see if there's a problem again.

It looks like it was something to do with the Cloudflare environment as you suggest. I've now set Cloudflare to full and strict encryption so it so that the certificate that's now seen is the Let's Encrypt one. 

Apparently from the Let's Encrypt forum "Let's Encrypt needs to check that you control your domain. It does this by placing a "token" in the .well-know/acme-challenge folder within your site, and then checking you can reach it externally. In your case this failed." https://community.letsencrypt.org/t/the-lets-encrypt-http-challenge-failed-invalid-response/26639/2

Hopefully the token will now be visible.
